name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - react-ui

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build project
        working-directory: frontend
        run: npm run build

      - name: Deploy to GitHub Pages (main branch)
        working-directory: frontend
        run: npx gh-pages -b main -d build
